# Generated by Django 3.2.9 on 2021-11-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip_code'),
    ]

    operations = [
      
    ]
